/*
Author: J.R. Diehl; edited by Ethan Van Sligtenhorst
Title: Header for Pokemon Class
*/

#ifndef POKEMON_H
#define POKEMON_H

#include <string>
#include <fstream>

// CreateSprite(head, body, arms, legs, type);
// NOTE: This function should be implemented using libjpeg

class Pokemon
{
private:
   int    index,          // Identification of individual Pokemon
          hp,             // Health of Pokemon
          defense;        // Ability of Pokemon to "deflect" attack damage
  string  type,           // Type of Pokemon (fire, water, earth, air)
          name;           // Name of Pokemon (randomly generated by type)

public:
  // CONSTRUCTORS
  Pokemon();
  Pokemon(int index, int hp, int defense, string type, string name);

  // SET & GET
  void setHP(int);
  int getHP();
  void setDefense(int);
  int getDefense();
  int getIndex();
  void setType(string);
  string getType();
  void setName(string);
  string getName();

  // COMBAT
  void damage(int);
  void heal(int);
  void sapDefense(int);
  void buffDefense(int);
  void attack1(Pokemon target);
  void attack2(Pokemon target);
  void attack3(Pokemon target);

  // DATA MANAGEMENT
  void writeData(ofstream& out);
  void readData(ifstream& in);
};

#endif // POKEMON_H
